server:
  port: 8513
#config:
#   userPath: http://192.168.0.100:8091/user/userInfo/getUserList
spring:
  application:
    name: Microservice-turbine
## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
#eureka信息配置
eureka:
  client:
    serviceUrl:
#      defaultZone: http://chendom:root123@localhost:8500/eureka/
      defaultZone: http://localhost:8500/eureka/
  instance:
     prefer-ip-address: true
#     #定制应用的名称
     instance-id: ${spring.application.name}:${server.port}
     metadata-map:
      cluster: Main
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000 #请求超时时间，默认是1分钟
