server:
  port: 8506
#config:
#   userPath: http://192.168.0.100:8091/user/userInfo/getUserList
spring:
  application:
    name: MyGateway
## INFO
info:
  app:
    name: ${project.artifactId}
    encoding: ${project.build.sourceEncoding}
    java:
      source: ${java.version}
      target: ${java.version}
#eureka信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
  instance:
     prefer-ip-address: true
#     #定制应用的名称
     instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: Zuul-Demo2
    api-b:
      path: /api-b/**
      service-id: Zuul-Demo3